# Generated by Django 3.1.2 on 2020-11-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200515_1225'),
        ('base', '0005_formfield_clean_name'),
    ]

    operations = [
    ]
